package io.surfworks.snakeburger.codegen;

import io.surfworks.snakeburger.stablehlo.StableHloAst;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Serializes StableHLO operations for embedding in generated classes.
 *
 * <p>Since StableHloAst uses sealed records, they are Serializable by default.
 * This serializer converts operations to a byte array format that can be
 * embedded in generated bytecode as a static field.
 */
public final class OperationSerializer {

    private OperationSerializer() {} // Utility class

    /**
     * Serializes a list of operations to a byte array.
     *
     * @param operations The operations to serialize
     * @return Serialized bytes
     * @throws CodegenException if serialization fails
     */
    public static byte[] serialize(List<StableHloAst.Operation> operations) throws CodegenException {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream();
             ObjectOutputStream oos = new ObjectOutputStream(baos)) {

            // Wrap operations in a serializable container
            SerializedOperations container = new SerializedOperations(operations);
            oos.writeObject(container);
            return baos.toByteArray();

        } catch (IOException e) {
            throw new CodegenException("Failed to serialize operations", e);
        }
    }

    /**
     * Deserializes operations from a byte array.
     *
     * @param bytes The serialized bytes
     * @return The deserialized operations
     * @throws CodegenException if deserialization fails
     */
    @SuppressWarnings("unchecked")
    public static List<StableHloAst.Operation> deserialize(byte[] bytes) throws CodegenException {
        try (ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
             ObjectInputStream ois = new ObjectInputStream(bais)) {

            SerializedOperations container = (SerializedOperations) ois.readObject();
            return container.operations();

        } catch (IOException | ClassNotFoundException e) {
            throw new CodegenException("Failed to deserialize operations", e);
        }
    }

    /**
     * Container for serialized operations.
     * Uses a simple wrapper to ensure proper serialization of the sealed types.
     */
    public record SerializedOperations(List<StableHloAst.Operation> operations) implements Serializable {
        // Serializable record - operations are serialized via their Serializable record implementations
    }
}
