/*
 * This source file was generated by the Gradle 'init' task
 */
package io.surfworks.warpforge.core.app;

import io.surfworks.warpforge.core.list.LinkedList;

import static io.surfworks.warpforge.core.utilities.StringUtils.join;
import static io.surfworks.warpforge.core.utilities.StringUtils.split;
import static io.surfworks.warpforge.core.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
