/*
 * This source file was generated by the Gradle 'init' task
 */
package io.surfworks.warpforge.core.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
