/*
 * This source file was generated by the Gradle 'init' task
 */
package io.surfworks.warpforge.core.utilities;

import io.surfworks.warpforge.core.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
